---
title: "cleaning_ectodecomposers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
```

#read in spec data¨and clean
```{r}
#need to align with SS metadata so need to read in
Meta.data.spatial<-read_csv("../clean_data/Clean_spatial_study_metadata.csv",show_col_types = FALSE)

#or the clusters combined with the SFSI - 1.5, 6 % - species and genus level 
SFSI.SS.specraw.1<-read_delim("../raw_data/all_tag_by_cluster_counts6318.txt",delim = ";",col_names = TRUE,trim_ws = FALSE,show_col_types = FALSE)
#SFSI.SS.specraw.6<-read_delim("../raw_data/all_tag_by_cluster_counts6354.txt",delim = ";",col_names = TRUE,trim_ws = FALSE,show_col_types = FALSE)


datasetlist<-list(SFSI.SS.specraw.1)#,SFSI.SS.specraw.6

#eperate dataset for the SS and SFSI
datasetlist.SFSI<-list()
datasetlist.SS<-list()
for (i in 1:length(datasetlist)){
datasetlist[[i]]<-separate(datasetlist[[i]], Tag, c("Year","Pool tag1","tag2"),sep = "_",extra = "merge")
datasetlist.SS[[i]]<-datasetlist[[i]][which(datasetlist[[i]]$Year == "Spatial"),]
datasetlist.SFSI[[i]]<-datasetlist[[i]][-which(datasetlist[[i]]$Year == "Spatial"),]
}

#SS clean----
for (i in 1:length(datasetlist.SS)) {
datasetlist.SS[[i]]<-separate(datasetlist.SS[[i]], tag2, c("tagx","tag1","prim","tagy","tag2"),sep = "_",extra = "merge")
datasetlist.SS[[i]]<-datasetlist.SS[[i]][,-which(colnames(datasetlist.SS[[i]]) %in% c("Year","tagx","prim","tagy"))]#remove columns that just have primer info etc
datasetlist.SS[[i]]$switches<-if_else(datasetlist.SS[[i]]$tag1 == datasetlist.SS[[i]]$tag2,1,0)
length(which(datasetlist.SS[[i]]$tag1 != datasetlist.SS[[i]]$tag2)) # should remove 14598 samples - leave with 468
datasetlist.SS[[i]]<-datasetlist.SS[[i]][-which(datasetlist.SS[[i]]$switches == 0),]
which(datasetlist.SS[[i]]$tag1 != datasetlist.SS[[i]]$tag2)#check they actually match
datasetlist.SS[[i]]<-datasetlist.SS[[i]][,-which(colnames(datasetlist.SS[[i]]) == "switches")]
datasetlist.SS[[i]]<-datasetlist.SS[[i]][-which(datasetlist.SS[[i]]$tag1 == 40),]#remove tag 40 -mock 
#load file with tag to sample name matching
tag.matches<-read_delim("../raw_data/spatial_tag_matching.txt",delim = "\t",col_names = TRUE,show_col_types = FALSE)
datasetlist.SS[[i]]<-separate(datasetlist.SS[[i]], `Pool tag1`,c("Pool","tag1"),sep = " ",extra="merge") #FYI this overwrite tag1 but now tag1 and tag2 are the same so its okay 
datasetlist.SS[[i]]$tag1<-paste(datasetlist.SS[[i]]$Pool,datasetlist.SS[[i]]$tag2) #again overwriting tag1 to make a combo column which I can more easily use to match with the tag matching file
tag.matches$tag1<-paste(tag.matches$Pool,tag.matches$Tag)
datasetlist.SS[[i]]<-datasetlist.SS[[i]][match(tag.matches$tag1,datasetlist.SS[[i]]$tag1),]#this should put in the same order and remove extras from SS file
datasetlist.SS[[i]]<-datasetlist.SS[[i]][,-2]
colnames(datasetlist.SS[[i]])[2]<-"tag1"
}


#SFSI
combine_rows <- function(data, row1, row2) {
  data[row2,5:ncol(data) ] <- data[row1,5:ncol(data) ] + data[row2,5:ncol(data) ]
  data[-row1, ]
}

datasetlist.SFSI.1<-datasetlist.SFSI
for (i in 1:length(datasetlist.SFSI)){
datasetlist.SFSI[[i]]<-separate(datasetlist.SFSI[[i]], `Pool tag1`,c("Pool","tag1"),sep = " ",extra="merge")#split columns again
datasetlist.SFSI[[i]]$switches<-if_else(datasetlist.SFSI[[i]]$tag1 == datasetlist.SFSI[[i]]$tag2,1,0)
datasetlist.SFSI[[i]]<-datasetlist.SFSI[[i]][-which(datasetlist.SFSI[[i]]$switches == 0),]
which(datasetlist.SFSI[[i]]$tag1 != datasetlist.SFSI[[i]]$tag2)#check they actually match
#identify the sample that have been rerun
datasetlist.SFSI[[i]][which(grepl("-",datasetlist.SFSI[[i]]$tag1)),1:4]

#if using a slightly different datset always check that row numbers are correct *** i.e `which(datasetlist.SFSI.1[[i]]$tag1 == "160337-1")`
datasetlist.SFSI.1[[i]]<-combine_rows(datasetlist.SFSI[[i]],which(datasetlist.SFSI[[i]]$tag1 == "242648-2"),which(datasetlist.SFSI[[i]]$tag1 == "242648-1"))
datasetlist.SFSI.1[[i]][which(grepl("-",datasetlist.SFSI.1[[i]]$tag1)),1:4]
datasetlist.SFSI.1[[i]]<-combine_rows(datasetlist.SFSI.1[[i]],which(datasetlist.SFSI.1[[i]]$tag1 == "159065-2"),which(datasetlist.SFSI.1[[i]]$tag1 == "159065-1"))
datasetlist.SFSI.1[[i]][which(grepl("-",datasetlist.SFSI.1[[i]]$tag1)),1:4]
datasetlist.SFSI.1[[i]]<-combine_rows(datasetlist.SFSI.1[[i]],which(datasetlist.SFSI.1[[i]]$tag1 == "242649-2"),which(datasetlist.SFSI.1[[i]]$tag1 == "242649-1"))
datasetlist.SFSI.1[[i]][which(grepl("-",datasetlist.SFSI.1[[i]]$tag1)),1:4]
datasetlist.SFSI.1[[i]]<-combine_rows(datasetlist.SFSI.1[[i]],which(datasetlist.SFSI.1[[i]]$tag1 == "155157-2"),which(datasetlist.SFSI.1[[i]]$tag1 == "155157-1"))
datasetlist.SFSI.1[[i]][which(grepl("-",datasetlist.SFSI.1[[i]]$tag1)),1:4]
datasetlist.SFSI.1[[i]]<-combine_rows(datasetlist.SFSI.1[[i]],which(datasetlist.SFSI.1[[i]]$tag1 == "160337-2"),which(datasetlist.SFSI.1[[i]]$tag1 == "160337-1"))
datasetlist.SFSI.1[[i]][which(grepl("-",datasetlist.SFSI.1[[i]]$tag1)),1:4]
datasetlist.SFSI[[i]]<-combine_rows(datasetlist.SFSI.1[[i]],which(datasetlist.SFSI.1[[i]]$tag1 == "158776-2"),which(datasetlist.SFSI.1[[i]]$tag1 == "158776-1"))

#can now remove the -2/-1 on the merge samples
datasetlist.SFSI[[i]]<-datasetlist.SFSI[[i]][,-4]#remove second tag column
datasetlist.SFSI[[i]]<-separate(datasetlist.SFSI[[i]],tag1,c("tag1","remove"),sep = "-")#there will be a warning because most samples do not have a "-" - should be 1782 warnings...
datasetlist.SFSI[[i]]<-datasetlist.SFSI[[i]][,-4]#remove the "remove" column
}


##need to put into the same order as the metadata 
Meta.data.spatial$pool_tag<-paste(Meta.data.spatial$pool,Meta.data.spatial$tag)
for (i in 1:length(datasetlist.SS)){
datasetlist.SS[[i]]$pool_tag<-paste(datasetlist.SS[[i]]$Pool,datasetlist.SS[[i]]$tag1)
datasetlist.SS[[i]]<-datasetlist.SS[[i]][match(Meta.data.spatial$pool_tag,datasetlist.SS[[i]]$pool_tag),]
print(which(Meta.data.spatial$tag != datasetlist.SS[[i]]$tag1))#check that they match now
}

#need to remove non-fungal taxa 
#read in taxonomic data 
taxsetlist<-list(read_csv("../clean_data/clean_taxonomicdata_SFSI_SS_1.5perc.csv"))#,read_csv("../clean_data/clean_taxonomicdata_SFSI_SS_5perc.csv")
taxsetlist.agar<-list(read_csv("../clean_data/clean_taxonimcdata_SFSI_SS_agar_1.5perc.csv"))#,read_csv("../clean_data/clean_taxonimcdata_SFSI_SS_agar_5perc.csv"))

NF.scata<-list()
for (i in 1:length(taxsetlist)){
NF.scata[[i]]<-taxsetlist[[i]][which(grepl("NF_",taxsetlist[[i]]$Reference)),]$`Cluster ID`
}

#remove the NF species hypothesis
for (i in 1:length(taxsetlist)){
datasetlist.SFSI[[i]]<-datasetlist.SFSI[[i]][,-which(colnames(datasetlist.SFSI[[i]]) %in% NF.scata[[i]])]
datasetlist.SS[[i]]<-datasetlist.SS[[i]][,-which(colnames(datasetlist.SS[[i]]) %in% NF.scata[[i]])]
}

```

#calculate relative abundance 
```{r}
#relative abundance SS data 
datasetlist.rel<-list()
for (i in 1:length(datasetlist.SS)) {
datasetlist.rel[[i]]<-datasetlist.SS[[i]][,-which(colnames(datasetlist.SS[[i]]) %in% c("Pool","tag1","pool_tag"))]/rowSums(datasetlist.SS[[i]][,-which(colnames(datasetlist.SS[[i]]) %in% c("Pool","tag1","pool_tag"))])
}

# 1.5 percent clustering SFSI
datasetlist.rel.sfsi<-datasetlist.SFSI[[1]][,-which(colnames(datasetlist.SFSI[[1]]) %in% c("Year","tag1","Pool"))]/rowSums(datasetlist.SFSI[[1]][,-which(colnames(datasetlist.SFSI[[1]]) %in% c("Pool","tag1","Year"))])
datasetlist.rel.sfsi$JordProvnr<-datasetlist.SFSI[[1]]$tag1

# 5 percent clustering SFSI
#datasetlist.rel.sfsi.genera<-datasetlist.SFSI[[2]][,-which(colnames(datasetlist.SFSI[[2]]) %in% c("Year","tag1","Pool"))]/rowSums(datasetlist.SFSI[[2]][,-which(colnames(datasetlist.SFSI[[2]]) %in% c("Pool","tag1","Year"))])
#datasetlist.rel.sfsi.genera$JordProvnr<-datasetlist.SFSI[[2]]$tag1

```

##make a genus level dataset of small-scale study 
```{r}
##read in data
taxsetlist.IDed<-read_csv('../clean_data/clean_taxonomicdata_SFSI_SS_genus.csv')

#first filter the rel abun data to exlcude the unclassfied and NF (aka. matched the TAaxsetlist.IDed which has the clean genus data)
datasetlist.rel.genus<-datasetlist.rel[[1]][,which(colnames(datasetlist.rel[[1]]) %in% taxsetlist.IDed$`Cluster ID`)]

#the column of species data is in exact same order as the row of the tax dataset so I can just replace colnames with genus name
which(colnames(datasetlist.rel.genus) != taxsetlist.IDed$`Cluster ID` )

scata.IDs.1<-colnames(datasetlist.rel.genus) #save them just incase i want again... 

colnames(datasetlist.rel.genus)<-taxsetlist.IDed$Genus

#remove columns where the colsums are zero (not present...)
datasetlist.rel.genus<-datasetlist.rel.genus[,-which(colSums(datasetlist.rel.genus) == 0)]
colnames(datasetlist.rel.genus)<-gsub("\\.[0-9]*","",colnames(datasetlist.rel.genus)) #this returns the column names to be repeated (not with .##)

#remove if not classfied to genus level 
datasetlist.rel.genus<-datasetlist.rel.genus[,which(colnames(datasetlist.rel.genus) %in% genera.list)]
colnames(datasetlist.rel.genus)<-gsub("\\.[0-9]*","",colnames(datasetlist.rel.genus)) #this returns the column names to be repeated (not with .##)

#some of the genera have only one species therefore do not need to be summed 
only.1.species.1<-c(names(table(colnames(datasetlist.rel.genus))[which(table(colnames(datasetlist.rel.genus)) < 2)] ))

#split the dataframe into two 
single.species.1<- datasetlist.rel.genus[,which(colnames(datasetlist.rel.genus) %in% only.1.species.1)] #198 genera
several.species.1<- datasetlist.rel.genus[,-which(colnames(datasetlist.rel.genus) %in% only.1.species.1)] # 757 species remaning
colnames(several.species.1)<-gsub("\\.[0-9]*","",colnames(several.species.1),perl=TRUE) #this returns the column names to be repeated (not with .##)

datasetlist.rel.genuslevel<-list() #make an empty list

for (i in 1:length(unique(colnames(several.species.1)))){
ind <- grepl(unique(colnames(several.species.1))[i], colnames(several.species.1)) #select the genus to sum
datasetlist.rel.genuslevel[[i]] <- rowSums(several.species.1[,ind]) #this sums them and enters each as an item on the list
}

#now I need to convert back from list to dataframe with correct column names
datasetlist.rel.genuslevel<- do.call(cbind.data.frame,datasetlist.rel.genuslevel)
colnames(datasetlist.rel.genuslevel)<-unique(colnames(several.species.1))

#now just double check that the values are as I would expect - these values shold match
sum(rowSums(datasetlist.rel.genus[,which(colnames(datasetlist.rel.genus) == "Suillus")])) ==sum(datasetlist.rel.genuslevel$Suillus)

#now add back the single species with cbind
datasetlist.rel.genus<-cbind(datasetlist.rel.genuslevel,single.species.1)
colnames(datasetlist.rel.genus) == unique(colnames(datasetlist.rel.genus)) #make sure not repeats
```

##make a genus level dataset of small-scale study - only for agaricomycetes 
```{r}
#first get just a agarciomycetes level SS dataframe 
#Filter out only the agaricos
datasetlist.rel.agar<-list()

for (i in 1:length(datasetlist.rel)){
datasetlist.rel.agar[[i]]<-datasetlist.rel[[i]][,which(colnames(datasetlist.rel[[i]]) %in% taxsetlist.agar[[i]][which(taxsetlist.agar[[i]]$Class == "Agaricomycetes"),]$`Cluster ID`)]
}

#the column of species data is in exact same order as the row of the tax dataset so I can just replace colnames with genus name
colnames(datasetlist.rel.agar[[1]]) == taxsetlist.agar[[1]]$`Cluster ID`

scata.IDs<-colnames(datasetlist.rel.agar[[1]]) #save them just incase i want again... 

colnames(datasetlist.rel.agar[[1]])<-taxsetlist.agar[[1]]$Genus

#remove columns where the colsums are zero (not present...)
datasetlist.rel.agar[[1]]<-datasetlist.rel.agar[[1]][,-which(colSums(datasetlist.rel.agar[[1]]) == 0)]
colnames(datasetlist.rel.agar[[1]])<-gsub("\\.[0-9]*","",colnames(datasetlist.rel.agar[[1]])) #this returns the column names to be repeated (not with .##)

#now just rowsum the columns with the same name... 
#https://stackoverflow.com/questions/25387714/add-columns-together-that-match-a-pattern

agar.genera.list<-c(unique(spec_database19[which(spec_database19$Class == "Agaricomycetes"),]$Genus))
agar.genera.list<-agar.genera.list[-3]#these remove the NA

#some of the genera have only one species therefore do not need to be summed 
only.1.species<-c(names(table(colnames(datasetlist.rel.agar[[1]]))[which(table(colnames(datasetlist.rel.agar[[1]])) < 2)] ))

#split the dataframe into two 
single.species<- datasetlist.rel.agar[[1]][,which(colnames(datasetlist.rel.agar[[1]]) %in% only.1.species)] #84 genera
several.species<- datasetlist.rel.agar[[1]][,-which(colnames(datasetlist.rel.agar[[1]]) %in% only.1.species)] # 659 species remaning
colnames(several.species)<-gsub("\\.[0-9]*","",colnames(several.species),perl=TRUE) #this returns the column names to be repeated (not with .##)

datasetlist.rel.agar.genus<-list() #make an empty list

for (i in 1:length(unique(colnames(several.species)))){
ind <- grepl(unique(colnames(several.species))[i], colnames(several.species)) #select the genus to sum
datasetlist.rel.agar.genus[[i]] <- rowSums(several.species[,ind]) #this sums them and enters each as an item on the list
}

#now I need to convert back from list to dataframe with correct column names
datasetlist.rel.agar.genus<- do.call(cbind.data.frame,datasetlist.rel.agar.genus)
colnames(datasetlist.rel.agar.genus)<-unique(colnames(several.species))

#now just double check that the values are as I would expect - these values shold match
sum(rowSums(datasetlist.rel.agar[[1]][,which(colnames(datasetlist.rel.agar[[1]]) == "Suillus")]))
sum(datasetlist.rel.agar.genus$Suillus)

#now add back the single species with cbind
datasetlist.rel.agar.genus<-cbind(datasetlist.rel.agar.genus,single.species)
colnames(datasetlist.rel.agar.genus) == unique(colnames(datasetlist.rel.agar.genus)) #make sure not repeats
```


#create filtered relative abun data
```{r}

##can be present at any level of relative abundance, present in at least 15 cores -evrything must be run together - variable names are resued!
#create the df
datasetlist.p2<-datasetlist.rel
datasetlist.p2.agar.genus<-datasetlist.rel.agar.genus
datasetlist.p2.genus<-datasetlist.rel.genus
#swith to presence absence
for (i in 1:length(datasetlist.p2)){
datasetlist.p2[[i]][datasetlist.p2[[i]] >0]<-1
}
datasetlist.p2.agar.genus[datasetlist.p2.agar.genus >0]<-1
datasetlist.p2.genus[datasetlist.p2.genus >0]<-1

#Filter out only the agaricos
datasetlist.p2.agar<-list()

for (i in 1:length(datasetlist.p2)){
datasetlist.p2.agar[[i]]<-datasetlist.p2[[i]][,which(colnames(datasetlist.p2[[i]]) %in% taxsetlist.agar[[i]][which(taxsetlist.agar[[i]]$Class == "Agaricomycetes"),]$`Cluster ID`)]
}


#filter out specs present in less than 15 cores
datasetlist.p2.15<-list()
datasetlist.p2.agar.15<-list()
for (i in 1:length(datasetlist.p2.agar)){
datasetlist.p2.15[[i]]<-datasetlist.p2[[i]][,-which(colSums(datasetlist.p2[[i]]) <15)]
datasetlist.p2.agar.15[[i]]<-datasetlist.p2.agar[[i]][,-which(colSums(datasetlist.p2.agar[[i]]) <15)]
}

datasetlist.p2.agar.genus.15<-datasetlist.p2.agar.genus[,-which(colSums(datasetlist.p2.agar.genus) <15)]
datasetlist.p2.genus.15<-datasetlist.p2.genus[,-which(colSums(datasetlist.p2.genus) <15)]

#make sure that the species are present in more than 2 sites at least for the datasets where all sites are together... 
#there is no taxa not present in more than 2 sites with the 25 threshold
counts_per_site.agar.15<-list()
counts_per_site.15<-list()
for (i in 1:length(datasetlist.p2.15)){
datasetlist.p2.agar.15[[i]]$site <-Meta.data.spatial$plot
datasetlist.p2.15[[i]]$site <-Meta.data.spatial$plot
counts_per_site.agar.15[[i]]<-aggregate(x= datasetlist.p2.agar.15[[i]][,-ncol(datasetlist.p2.agar.15[[i]])],by=list(datasetlist.p2.agar.15[[i]]$site),FUN=sum)
counts_per_site.agar.15[[i]][counts_per_site.agar.15[[i]]>0]<-1
datasetlist.p2.agar.15[[i]]<-datasetlist.p2.agar.15[[i]][,- c(which(colSums(counts_per_site.agar.15[[i]][,-1]) == 1),which(colSums(counts_per_site.agar.15[[i]][,-1]) == 2))]
counts_per_site.15[[i]]<-aggregate(x= datasetlist.p2.15[[i]][,-ncol(datasetlist.p2.15[[i]])],by=list(datasetlist.p2.15[[i]]$site),FUN=sum)
counts_per_site.15[[i]][counts_per_site.15[[i]]>0]<-1
datasetlist.p2.15[[i]]<-datasetlist.p2.15[[i]][,- c(which(colSums(counts_per_site.15[[i]][,-1]) == 1),which(colSums(counts_per_site.15[[i]][,-1]) == 2))]
}

datasetlist.p2.agar.genus.15$site <-Meta.data.spatial$plot
counts_per_site.agar.genus.15<-aggregate(x= datasetlist.p2.agar.genus.15[,-ncol(datasetlist.p2.agar.genus.15)],by=list(datasetlist.p2.agar.genus.15$site),FUN=sum)
counts_per_site.agar.genus.15[counts_per_site.agar.genus.15>0]<-1
datasetlist.p2.agar.genus.15<-datasetlist.p2.agar.genus.15[,- c(which(colSums(counts_per_site.agar.genus.15[,-1]) == 1),which(colSums(counts_per_site.agar.genus.15[,-1]) == 2))]

datasetlist.p2.genus.15$site <-Meta.data.spatial$plot
counts_per_site.genus.15<-aggregate(x= datasetlist.p2.genus.15[,-ncol(datasetlist.p2.genus.15)],by=list(datasetlist.p2.genus.15$site),FUN=sum)
counts_per_site.genus.15[counts_per_site.genus.15>0]<-1
datasetlist.p2.genus.15<-datasetlist.p2.genus.15[,- c(which(colSums(counts_per_site.genus.15[,-1]) == 1),which(colSums(counts_per_site.genus.15[,-1]) == 2))]

#flip back to the relative abundance data 
datasetlist.rel.15<-list()
datasetlist.rel.agar.15<-list()
for (i in 1:length(datasetlist.p2.agar)){
datasetlist.rel.15[[i]]<-datasetlist.rel[[i]][,which(colnames(datasetlist.rel[[i]]) %in% colnames(datasetlist.p2.15[[i]]))]
datasetlist.rel.agar.15[[i]]<-datasetlist.rel[[i]][,which(colnames(datasetlist.rel[[i]]) %in% colnames(datasetlist.p2.agar.15[[i]]))]
}

datasetlist.rel.agar.genus.15<-datasetlist.rel.agar.genus[,which(colnames(datasetlist.rel.agar.genus) %in% colnames(datasetlist.p2.agar.genus.15))]
datasetlist.rel.genus.15<-datasetlist.rel.genus[,which(colnames(datasetlist.rel.genus) %in% colnames(datasetlist.p2.genus.15))]

```


#make ecto relative abun of sfsi 1.5%
```{r}
#make ecto only data set 
datasetlist.ecm.sfsi<-datasetlist.SFSI[[1]][,which(colnames(datasetlist.SFSI[[1]]) %in% taxsetlist[[1]][which(taxsetlist[[1]]$Ecology == "ECM"),]$`Cluster ID`)]
#only 3 percent

#remove samples where there are no ectos...
datasetlist.ecm.sfsi$JordProvnr<-datasetlist.SFSI[[1]]$tag1

datasetlist.ecm.sfsi<-datasetlist.ecm.sfsi[-which(rowSums(datasetlist.ecm.sfsi[,-which(colnames(datasetlist.ecm.sfsi) == "JordProvnr")]) == 0),]

datasetlist.rel.sfsi.ecm<-datasetlist.ecm.sfsi[,-which(colnames(datasetlist.ecm.sfsi) == "JordProvnr")]/rowSums(datasetlist.ecm.sfsi[,-which(colnames(datasetlist.ecm.sfsi) == "JordProvnr")])

datasetlist.rel.sfsi.ecm$JordProvnr<-datasetlist.ecm.sfsi$JordProvnr


```



#write clean files
```{r}

perc<-list("1.5")
for(x in 1:length(perc)){
   write.csv(datasetlist.rel.15[[x]],file = paste('../clean_data/','SS_data_relabun_15_',perc[x],'perc','.csv',sep=""), row.names = F)
}

for(x in 1:length(perc)){
   write.csv(datasetlist.rel.agar.15[[x]],file = paste('../clean_data/','SS_data_relabun_agar_15_',perc[x],'perc','.csv',sep=""), row.names = F)
}

write.csv(datasetlist.rel.agar.genus.15,file = '../clean_data/SS_data_relabun__agar_genus_15.csv', row.names = F)
write.csv(datasetlist.rel.genus.15,file = '../clean_data/SS_data_relabun_genus_15.csv', row.names = F)

write_csv(datasetlist.rel.sfsi,"../clean_data/SFSI_data_relabun_1.5perc.csv")
write_csv(datasetlist.rel.sfsi.ecm,"../clean_data/SFSI_data_relabun_ECM_1.5perc.csv")
```

