---
title: "cleam_ectodecomposer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(dplyr)
library(tidyr)
```


#read in data
```{r}
SFSI.soil<-read_delim("../raw_data/SFSI_soil_till_2022.csv",delim = ";",show_col_types = FALSE)
datasetlist.rel.sfsi<-read_csv("../clean_data/SFSI_data_relabun_1.5perc.csv")
datasetlist.rel.sfsi.ecm<-read_csv("../clean_data/SFSI_data_relabun_ECM_1.5perc.csv")
```

#create CN, NC, mineral content and Cstocks
```{r}
SFSI.soil$CN<-SFSI.soil$C/SFSI.soil$N
SFSI.soil$NC<-SFSI.soil$N/SFSI.soil$C
SFSI.soil$Cstock<-SFSI.soil$H_mangd*SFSI.soil$C
SFSI.soil$mincon<-1-((0.01*SFSI.soil$C)/0.50)
```

#transform
```{r}
SFSI.soil$Cstock_log<-log(SFSI.soil$Cstock)
SFSI.soil$CN_log<-log(SFSI.soil$CN)
SFSI.soil$mincon_sqrt<-sqrt(SFSI.soil$mincon)#this generates NAs bc of negatives
SFSI.soil[which(is.na(SFSI.soil$mincon_sqrt)),]$mincon_sqrt<-0
SFSI.soil$pH_H2O_log<-log(SFSI.soil$pH_H2O)
SFSI.soil$Bestandsalder_log<-log(SFSI.soil$Bestandsalder)
```

#inspect and fitering soil data
```{r}
#lets see the range and distribution of stand age
hist(SFSI.soil$Bestandsalder) # skewed towards young forests - mostly < 100 
quantile(SFSI.soil$Bestandsalder) # 50% of sites 48 years or younger

#the humus form
table(SFSI.soil$H_form) #no 0 - want to only include sites with H_form = 1,2,3 = Mor 1, Mor 2 and Moder 
length(SFSI.soil[SFSI.soil$H_form %in% c("1","2","3"),]$H_form) #1420 samples 

#proportion pine, spruce, mix
table(SFSI.soil$Tallandel) # 311 sites 100% pine
table(SFSI.soil$Granandel) # 212 sites 100% spruce 
length(SFSI.soil[which(SFSI.soil$Tallandel > 0 & SFSI.soil$Granandel >0),]$Tallandel) #665 sites with pine spruce mix

#one site with a strange CN ratio - which is that
hist(SFSI.soil$CN) # one is >200?
which(SFSI.soil$CN >200) # row 717 # 100 % stand of 167 years #JordProvnr 204631

#land use distribution
table(SFSI.soil$Agoslag) # mostly "productive forest" 999 samples

SFSI.soil.f1<-SFSI.soil[which(SFSI.soil$Bestandsalder >10),]
SFSI.soil.f1<-SFSI.soil.f1[which(SFSI.soil.f1$Agoslag == 1),]
SFSI.soil.f1<-SFSI.soil.f1[-which(SFSI.soil.f1$Tallandel+SFSI.soil.f1$Granandel < 90),]
SFSI.soil.f1<-SFSI.soil.f1[which(SFSI.soil.f1$CN < 200),]
SFSI.soil.f1<-SFSI.soil.f1[which(between(SFSI.soil.f1$Temperatursumma,1100,1500)),]
SFSI.soil.f1<-SFSI.soil.f1[-which(SFSI.soil.f1$pH_H2O > 6),]

#SFSI.soil.f1<-SFSI.soil.f1[which(SFSI.soil.f1$H_form %in% c("1","2","3")),] 
 
length(setdiff(SFSI.soil.f1$JordprovNr,datasetlist.rel.sfsi$JordProvnr))
length(setdiff(datasetlist.rel.sfsi$JordProvnr,SFSI.soil.f1$JordprovNr))

#make sure that the soil data and species data is matching

SFSI.soil.f2<-SFSI.soil.f1[-which(SFSI.soil.f1$JordprovNr %in% setdiff(SFSI.soil.f1$JordprovNr,datasetlist.rel.sfsi$JordProvnr)),] # remove 23
datasetlist.rel.sfsi.f2<-datasetlist.rel.sfsi[-which(datasetlist.rel.sfsi$JordProvnr %in% setdiff(datasetlist.rel.sfsi$JordProvnr,SFSI.soil.f1$JordprovNr)),] #remove 6 
datasetlist.rel.sfsi.ecm.f1<-datasetlist.rel.sfsi.ecm[-which(datasetlist.rel.sfsi.ecm$JordProvnr %in% setdiff(datasetlist.rel.sfsi.ecm$JordProvnr,SFSI.soil.f1$JordprovNr)),]
#this removes samples which then means some taxa have zero relative abundances across the remaining samples
datasetlist.rel.sfsi.ecm.f1<-datasetlist.rel.sfsi.ecm.f1[,-which(colSums(datasetlist.rel.sfsi.ecm.f1[,-371])==0)]

#now match the rows of species data to the order of sfsi
datasetlist.rel.sfsi.f2<-datasetlist.rel.sfsi.f2[match(SFSI.soil.f2$JordprovNr,datasetlist.rel.sfsi.f2$JordProvnr),]
length(which(datasetlist.rel.sfsi.f2$JordProvnr != SFSI.soil.f2$JordprovNr))
datasetlist.rel.sfsi.ecm.f1<-datasetlist.rel.sfsi.ecm.f1[match(SFSI.soil.f2$JordprovNr,datasetlist.rel.sfsi.ecm.f1$JordProvnr),]
length(which(datasetlist.rel.sfsi.ecm.f1$JordProvnr != SFSI.soil.f2$JordprovNr))
```

#write cleaned data files
```{r}
write_csv(SFSI.soil,"../clean_data/Clean_SFSI_soil_data.csv")
write_csv(SFSI.soil.f2,"../clean_data/Clean_filtered_SFSI_soil_data.csv")
write_csv(datasetlist.rel.sfsi.f2, "../clean_data/SFSI_data_relabun_1.5perc_filtered.csv")
write_csv(datasetlist.rel.sfsi.ecm.f1, "../clean_data/SFSI_data_relabun_ECM_1.5perc_filtered.csv")
```

