---
title: "analysis_ectodecomposers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# META:
# Created by: Cristofer Engberg Hydén - Edited by Erica Packard
# Date: 2023-10-16
```

#load packages
```{r}
library(tidyverse)  # General data management (+ ggplot2)
library(dbplyr)     # Addition to tidyverse (dplyr) - more database functionalities
library(DBI)        # Handle database connections and SQL-code
library(odbc)       # Handle the local computers ODBC-connections
library(sf)         # Simple Features, handle .shp-filer, geographical data and coordinates
library(tmap)       # Like ggplot2 but specifically for creating maps
library(patchwork)
library(ggplot2)
library(grid)
```

#   Read in data 
##  Data: 
```{r}
SFSI.soil.f2<-read_csv("../clean_data/Clean_filtered_SFSI_soil_data.rev.csv")
SFSI.soil<-read_delim("../raw_data/SFSI_NFI_data_20240627_reduced.csv",delim = ";",show_col_types = FALSE)
SS.coordinates<-read_delim("../raw_data/Spatial_study_coordinates.csv",delim = ";",col_types = list("c","n","n","f","f"))
```

##  Maps:
```{r}
sverige <- st_read("../gis/Sverige.shp", stringsAsFactors=FALSE) %>% 
  st_transform(crs = "EPSG:3006")  # Is in coordinate system RT90, converts into SWEREF 99TM

sverige_simp <- st_simplify(sverige, dTolerance = 2000) ## Simplifies the border of Sweden (possibly good to do if the resulting map is smaller(?))

sjoar <- st_read("../gis/lakes_swe99.shp", stringsAsFactors=FALSE)

sjoar <- st_intersection(st_geometry(sjoar), st_geometry(sverige)) ## Removes any lakes beyond the border of Sweden
```

#   Wrangle data

```{r}
#rename spruce pine variable 
SS.coordinates$Species<-if_else(SS.coordinates$Species == "Spruce","Spruce dominated","Pine dominated")
#Hade, 17472,17646 overlap to much to distinguish add a manual jitter to 17472 and 17646
SS.coordinates[2,2]<-60.30000
SS.coordinates[2,3]<-17.04000
SS.coordinates[12,3]<-17.09000
SS.coordinates[12,2]<-60.28000

# test filtering
#SFSI.soil.f1<-SFSI.soil[which(SFSI.soil$Bestandsalder >10),] #remove sites mean stand age 10 and under
#SFSI.soil.f1<-SFSI.soil.f1[which(SFSI.soil.f1$Agoslag == 1),] #only productive forests
#SFSI.soil.f1<-SFSI.soil.f1[-which(SFSI.soil.f1$Tallandel+SFSI.soil.f1$Granandel < 90),] # > 90 conifers
#SFSI.soil.f1<-SFSI.soil.f1[-which(SFSI.soil.f1$CN < 200),] #remove CN outlier
#SFSI.soil.f1<-SFSI.soil.f1[-which(SFSI.soil.f1$pH_H2O > 6),] # remove more alkaline soils
#SFSI.soil.f1<-SFSI.soil.f1[-which(is.na(SFSI.soil.f1$Mn_Ac)),] #remove missing data
#SFSI.soil.f1<-SFSI.soil.f1[which(between(SFSI.soil.f1$Temperatursumma,1000,1425)),]

#create spruce pine variable
SFSI.soil.f2$host<-if_else(SFSI.soil.f2$Granandel >= 60,"Spruce",if_else(SFSI.soil.f2$Tallandel >= 60,"Pine","Mixed")) 
```


# Make the data into georeferenced object:
```{r}
data_sf_sfsi <- st_as_sf(SFSI.soil.f2, coords = c("Ost_Stord","Nord_Stord"),
                    crs = "EPSG:3006", agr = "constant")
data_sf_ss<- st_as_sf(SS.coordinates, coords = c("Longitude","Latitude"), agr = "constant")
```

# test:
```{r}
plot(data_sf_sfsi)
plot(data_sf_ss)
```


#   Create map
```{r}
# tm_shape() for the object folowed by a tm_...() for the appropriate plotting tool
#  for the data (eg polygon, dots, raster etc...) and then keep adding ontop of the
#  previous.

map1 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_sf_sfsi["host"]) +
  tm_dots(col = "host", size = 0.25,alpha=0.5,shape=19,palette=c("#448C3F","#AACB90","#415B25"),title = "National samples",legend.show = FALSE)+
  #tm_shape(data_sf_ss["Species"]) +
  #tm_dots(col = "Species", size = 0.25,shape = 1,palette=c("orange","darkred"),title = "Regional samples",legend.show = FALSE)+
  tm_add_legend(type = "symbol",shape =19 ,col = c("#448C3F","#AACB90","#415B25"),labels = c("Mixed","Pine dominated", "Spruce dominated" ),title = "Large-scale samples")+
  tm_add_legend(type = "symbol",shape =19 ,col = c("#A5D7E6","#32219B"),labels = c("Pine dominated", "Spruce dominated"),title = "Small-scale samples")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

map2 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_sf_sfsi["Bestandsalder"]) +
  tm_dots(col = "Bestandsalder", size = 0.25,alpha = 0.5,shape=19,palette="OrRd",n = 5,contrast = c(0.2, 1),title = "National samples",legend.show = F)+
  #tm_shape(data_sf_ss["Age"]) +
  #tm_dots(col = "Age", size = 0.25,shape = 1,palette=c("navy","dodgerblue"),title = "Regional samples",legend.show = F)+
  tm_add_legend(type = "symbol",shape=19,col=c(tmaptools::get_brewer_pal("OrRd", 5, plot = FALSE)),labels = c("10-50", "50-100","100-150","150-200","200+"),title = "National samples")+
  tm_add_legend(type = "symbol",shape=19,col = c("navy","dodgerblue"),labels = c("Old > 80 years", "Young 15-20 years"),title = "Regional samples")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

map3 <- tm_shape(sverige,bbox = c(xmin=600000,ymin=6613368,xmax=712000,ymax=6700000)) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1)+ 
  tm_shape(sjoar,bbox = c(xmin=600000,ymin=6613368,xmax=712000,ymax=6700000)) +
  tm_fill(col = "lightblue")+
  tm_shape(data_sf_ss["Species"]) +
  tm_dots(col = "Species", size = 12.0,border.lwd=4,alpha = 0.5,shape=19,palette=c("#A5D7E6","#32219B"),title = "Regional samples",legend.show = FALSE)

map4 <- tm_shape(sverige,bbox = c(xmin=600000,ymin=6613368,xmax=712000,ymax=6700000)) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1)+ 
  tm_shape(sjoar,bbox = c(xmin=600000,ymin=6613368,xmax=712000,ymax=6700000)) +
  tm_fill(col = "lightblue")+
  tm_shape(data_sf_ss["Age"]) +
  tm_dots(col = "Age", size = 12.0,border.lwd=4,alpha = 0.5,shape=19,palette=c("navy","dodgerblue"),title = "Regional samples",legend.show = FALSE)


```


# show in plot viewer:
```{r}
map1
map2
map3
map4

# All sizes are relative to the size of the plot so look at exported file (the
#  step below) to see what needs adjusting. Don't try to make it look good in R/
#  Rstudios plotting window but in the exported file that will be used.
```

#   Save data
```{r}
tmap_save(tm = map1, filename = "../figures/revised/Sampling_map.png",dpi = 1000)
tmap_save(tm = map3, filename = "../figures/Sampling_map_inset.png")
tmap_save(tm = map2, filename = "../figures/Age_map.png",dpi = 1000)
tmap_save(tm = map4, filename = "../figures/Age_map_inset.png")

tmap_save(tm = map1, filename = "../figures/revised/Sampling_map.pdf")
tmap_save(tm = map1, filename = "../figures/Sampling_map.eps")
tmap_save(tm = map3, filename = "../figures/Sampling_map_inset.pdf")
tmap_save(tm = map2, filename = "../figures/revised/Age_map.pdf")
tmap_save(tm = map4, filename = "../figures/revised/Age_map_inset.pdf")
```



