---
title: "analysis_ectodecomposers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# META:
# Created by: Cristofer Engberg Hydén - Edited by Erica Packard
# Date: 2023-10-16
```

#load packages
```{r}
library(tidyverse)  # General data management (+ ggplot2)
library(dbplyr)     # Addition to tidyverse (dplyr) - more database functionalities
library(DBI)        # Handle database connections and SQL-code
library(odbc)       # Handle the local computers ODBC-connections
library(sf)         # Simple Features, handle .shp-filer, geographical data and coordinates
library(tmap)       # Like ggplot2 but specifically for creating maps
```

#   Read in data 
##  Data: 
```{r}
clean_soil_data<-read_csv("../clean_data/Clean_SFSI_soil_data.csv")
SFSI.spec<-read_csv("../clean_data/SFSI_data_relabun_1.5perc.csv")
```

##  Maps:
```{r}
sverige <- st_read("../gis/Sverige.shp", stringsAsFactors=FALSE) %>% 
  st_transform(crs = "EPSG:3006")  # Is in coordinate system RT90, converts into SWEREF 99TM

sverige_simp <- st_simplify(sverige, dTolerance = 2000) ## Simplifies the border of Sweden (possibly good to do if the resulting map is smaller(?))

sjoar <- st_read("../gis/lakes_swe99.shp", stringsAsFactors=FALSE)

sjoar <- st_intersection(st_geometry(sjoar), st_geometry(sverige)) ## Removes any lakes beyond the border of Sweden
```

#   Wrangle data

```{r}
#first match the spec data and the coordinate data 
SFSI.spec<-SFSI.spec[which(SFSI.spec$JordProvnr %in% clean_soil_data$JordprovNr),]
clean_soil_data<-clean_soil_data[match(SFSI.spec$JordProvnr,clean_soil_data$JordprovNr),]
which(SFSI.spec$JordProvnr != clean_soil_data$JordprovNr)

#isolate C. cinnamomeus 
SFSI.spec.cinna<- SFSI.spec[,which(colnames(SFSI.spec) == "scata6318_68")]
SFSI.spec.cinna.p<-SFSI.spec.cinna
SFSI.spec.cinna.p[SFSI.spec.cinna.p>0]<-1
SFSI.spec.cinna.p2<-SFSI.spec.cinna
SFSI.spec.cinna.p2[SFSI.spec.cinna.p2>0.01]<-1
SFSI.spec.cinna.p2[SFSI.spec.cinna.p2<0.01]<-0

#isolate C. comptulus
SFSI.spec.comp<- SFSI.spec[,which(colnames(SFSI.spec) == "scata6318_252")]
SFSI.spec.comp.p<-SFSI.spec.comp
SFSI.spec.comp.p[SFSI.spec.comp.p>0]<-1
SFSI.spec.comp.p2<-SFSI.spec.comp
SFSI.spec.comp.p2[SFSI.spec.comp.p2>0.01]<-1
SFSI.spec.comp.p2[SFSI.spec.comp.p2<0.01]<-0

#create new df of just hyst, gaut and coordinates 
cort_data<-cbind(clean_soil_data$Ost_Stord,clean_soil_data$Nord_Stord,SFSI.spec.comp.p,SFSI.spec.cinna.p,SFSI.spec.comp.p2,SFSI.spec.cinna.p2)
colnames(cort_data)<-c("Ost_Stord","Nord_Stord","C.comptulus>0","C.cinnamomeus>0","C.comptulus>0.01","C.cinnamomeus>0.01")
```


# Make the data into georeferenced object:
```{r}
data_corts <- st_as_sf(cort_data, coords = c("Ost_Stord","Nord_Stord"),
                    crs = "EPSG:3006", agr = "constant")
```

# test:
```{r}
plot(data_corts,max.plot = 48)

```


#   Create map
```{r}
# tm_shape() for the object folowed by a tm_...() for the appropriate plotting tool
#  for the data (eg polygon, dots, raster etc...) and then keep adding ontop of the
#  previous.

map1 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_corts[-which(data_corts$`C.comptulus>0` == 0),]["C.comptulus>0"]) +
  tm_dots(col = "C.comptulus>0", size = 0.25,shape = 1,palette=c("darkred"),title = "C. comptulus presence")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

map2 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_corts[-which(data_corts$`C.comptulus>0.01` == 0),]["C.comptulus>0.01"]) +
  tm_dots(col = "C.comptulus>0.01", size = 0.25,shape = 1,palette=c("darkred"),title = "C. comptulus presence over 1%")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

map3 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_corts[-which(data_corts$`C.cinnamomeus>0` == 0),]["C.cinnamomeus>0"]) +
  tm_dots(col = "C.cinnamomeus>0", size = 0.25,shape = 1,palette=c("darkred"),title = "C. cinnamomeus presence")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

map4 <- tm_shape(sverige_simp) +
  tm_polygons(border.col = "black", col = "white", alpha = 0.1) +
  tm_shape(sjoar) +
  tm_fill(col = "lightblue") +
  tm_shape(data_corts[-which(data_corts$`C.cinnamomeus>0.01` == 0),]["C.cinnamomeus>0.01"]) +
  tm_dots(col = "C.cinnamomeus>0.01", size = 0.25,shape = 1,palette=c("darkred"),title = "C. cinnamomeus presence over 1%")+
  tm_layout(legend.width = 1,legend.outside = TRUE,legend.position = c(-0.15,0.1),frame = FALSE)

# ... + tm_layout() to format titles, legend, margins ...
```


# show in plot viewer:
```{r}
map1
map2
map3
map4
# All sizes are relative to the size of the plot so look at exported file (the
#  step below) to see what needs adjusting. Don't try to make it look good in R/
#  Rstudios plotting window but in the exported file that will be used.
```

#   Save data
```{r}
tmap_save(tm = map1, filename = "../figures/C.comptulus_map.png")
tmap_save(tm = map2, filename = "../figures/C.comptulus1perc_map.png")
tmap_save(tm = map3, filename = "../figures/C.cinnamomeus_map.png")
tmap_save(tm = map4, filename = "../figures/C.cinnamomeus1perc_map.png")
```



