---
title: "Making_fasta_files"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load package
```{r}
library(readr)
```


#load data
```{r}
datasetlist.rel.15<-read_csv("../clean_data/SS_data_relabun_15_1.5perc.rev.csv")
taxsetlist<-list(read_csv("../clean_data/clean_taxonomicdata_SFSI_SS_1.5percrev.csv"))

##read in WAE results
WAE.results<-read_csv("../clean_data/WAE_results.sig.csv")
WAE.results.oppo<-read_csv("../clean_data/WAE_results.oppo.sig.csv")
```

#format sig species
```{r}
wae.seqs<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% WAE.results$Cluster_ID),]$Sequence1
wae.ids<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% WAE.results$Cluster_ID),]$`Cluster ID`
WAE.results<-WAE.results[match(wae.ids,WAE.results$Cluster_ID),]

wae.fasta<-paste(">",wae.ids,WAE.results$Genus,WAE.results$species,"\n",wae.seqs,"\n")
```

#format sig species oppo
```{r}
wae.seqs.oppo<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% WAE.results.oppo$Cluster_ID),]$Sequence1
wae.ids.oppo<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% WAE.results.oppo$Cluster_ID),]$`Cluster ID`
WAE.results.oppo<-WAE.results.oppo[match(wae.ids.oppo,WAE.results.oppo$Cluster_ID),]

wae.fasta.oppo<-paste(">",wae.ids.oppo,WAE.results.oppo$Genus,WAE.results.oppo$species,"\n",wae.seqs.oppo,"\n")
```

#format all with no id
```{r}
test.pres.noid<-datasetlist.rel.15

test.pres.noid<-datasetlist.rel.15[,which(colnames(datasetlist.rel.15) %in% taxsetlist[[1]][which(is.na(taxsetlist[[1]]$Reference)),]$`Cluster ID`)]

noidseqs<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% colnames(test.pres.noid)),]$Sequence1
noidscata<-taxsetlist[[1]][which(taxsetlist[[1]]$`Cluster ID` %in% colnames(test.pres.noid)),]$`Cluster ID`
noid.fasta<-paste(">",noidscata,"\n",noidseqs,"\n")
```

#save
```{r}
sink("../clean_data/fasta_no_ID_SS.rev.txt")
cat(noid.fasta)
sink()

sink("../clean_data/fasta_sig_species.txt")
cat(wae.fasta)
sink()

sink("../clean_data/fasta_sig_species.oppo.txt")
cat(wae.fasta.oppo)
sink()
```

